CREATE DATABASE sales;
USE  sales;
select * from sales.brands;
select * from sales.categories;
select * from sales.customers;
select * from sales.order_items;
select * from sales.orders;
select * from sales.products;
select * from sales.staffs;
select * from sales.stocks;
select * from sales.stores;

-- task 3
 --  Inner Join for Order Details 
-- Join orders, order_items, and products to display detailed line items.

-- Task 3: Inner Join for Order Details
select * from sales.orders as o
inner join sales.order_items as i
on  o.order_id=i.order_id
inner join sales.products as p
on i.product_id=p.product_id;

-- task 4
-- 4. Total Sales by Store 
--  Write a query to group sales (total_price) by each store_id.
-- Task 4: Total Sales by Store
select st.store_name,sum(a.total_price) as total_price
from sales.order_items as a
inner join sales.orders as o
on o.order_id=a.order_id
inner join sales.stores as  st
on o.store_id=st.store_id
group by st.store_name;
-- task 5
-- 5. Top 5 Selling Products 
--  Use ORDER BY and LIMIT to get the top 5 most sold products by quantity.
-- Task 5: Top 5 Selling Products

select p.product_id,p.product_name,sum(o.quantity) as total_quantity
from sales.order_items as o
inner join sales.products as p
on o.product_id = p.product_id
group by p.product_id, p.product_name
order by total_quantity desc
limit 5;
-- 6. Customer Purchase Summary 
-- For each customer, return total orders placed, total items purchased, and total revenue.
select c.customer_id,c.first_name,count(o.order_id)as total_orders,sum(i.quantity)as total_items,sum(i.total_price) as total_revenue
from sales.customers as c
inner join sales.orders as o
on  c.customer_id=o.customer_id
inner join sales.order_items as i
on o.order_id=i.order_id
group by c.customer_id,c.first_name
order by total_revenue;
-- 7. Segment Customers by Total Spend 
--  Write a query to classify customers into spending brackets (e.g., low, medium, high).
select c.customer_id,c.first_name,sum(i.total_price)as spending_amount,
case
when  sum(i.total_price) < 1000 then'Low'
when sum(i.total_price) between 1000 and 7000 then 'Medium'
when sum(i.total_price) > 7000 then 'High'
else "na"
end as total_price
from sales.customers as c
inner join sales.orders as o
on c.customer_id=o.customer_id
inner join sales.order_items as i
on o.order_id=i.order_id
group by c.customer_id,c.first_name;
-- 8. Staff Performance Analysis 
--  Analyze total revenue generated by each staff member based on their handled orders.
select s.staff_id,s.first_name,sum (o.total_price) as total_revenue
from sales.staffs as s
inner join sales.orders as i
on s.staff_id=i.staff_id
inner join sales.order_items as o
on i.order_id=o.order_id
group by s.staff_id,s.first_name;

select s.staff_id,s.first_name, sum(o.quantity * o.list_price * (1 - o.discount)) AS total_revenue
from sales.staffs as s
inner join sales.orders as i
on s.staff_id=i.staff_id
inner join sales.order_items as o
on i.order_id=o.order_id
group by s.staff_id,s.first_name;
-- 9 Stock Alert Query  Write a query to list products where stock quantity < 10 in any store.
select p.product_id,p.product_name,s.store_id,s.quantity
from sales.products as p
inner join sales.stocks as s
on p.product_id=s.product_id
where s.quantity<10;


-- 10. Create Final Segmentation Table 
-- Create a table customer_segments that will be populated from Python ML results later.

SELECT * FROM sales.customer_segments;


