CREATE DATABASE sales;
USE  sales;
select * from sales.brands;
select * from sales.categories;
select * from sales.customers;
select * from sales.order_items;
select * from sales.orders;
select * from sales.products;
select * from sales.staffs;
select * from sales.stocks;
select * from sales.stores;